name: build
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: yarn && yarn package
      - uses: ./
        with:
          dist: 'docs'
          ghToken: ${{ secrets.GITHUB_TOKEN }}
